=== yixianUvA/extended_heptane_svn/doc/annot.dtd
<!-- *************************************************************
Format of the WCET analysis annotation files
************************************************************** -->
<!ELEMENT ANNOT (CFG*)>

<!ELEMENT CFG (BB*) (LOOP*)>
<!ATTLIST CFG name CDATA #REQUIRED>

<!-- Loop annotations -->
<!ELEMENT LOOP (LOOP*)>
<!ATTLIST LOOP maxiter NMTOKEN #REQUIRED>

<!-- Basic block annotations -->
<!-- Address = address of BB, 
     annotname = annotation name, value = annotation value -->
<!ELEMENT BB>
<!ATTLIST BB address NMTOKEN #REQUIRED>
<!ATTLIST BB annotname CDATA #REQUIRED>
<!ATTLIST BB value NMTOKEN #REQUIRED>

=== yixianUvA/extended_heptane_svn/doc/fft.annot.xml
<!DOCTYPE ANNOT SYSTEM "annot.dtd">
<ANNOT>
<CFG name="fabs">
</CFG>
<CFG name="log">
</CFG>
<CFG name="sin">
  <LOOP maxiter="8">
  </LOOP>
</CFG>
<CFG name="cos">
</CFG>
<CFG name="fft1">
  <LOOP maxiter="4">
  </LOOP>
  <LOOP maxiter="4">
    <LOOP maxiter="4">
      <LOOP maxiter="4">
      </LOOP>
    </LOOP>
  </LOOP>
  <LOOP maxiter="7">
    <LOOP maxiter="2">
    </LOOP>
  </LOOP>
  <LOOP maxiter="8">
  </LOOP>
</CFG>
<CFG name="main">
  <LOOP maxiter="8">
  </LOOP>
</CFG>
</ANNOT>
