=== yixianUvA/extended_heptane_svn/doc/cfglib.dtd
<!-- *************************************************************
Format of the cfglib XML files
************************************************************** -->

<!ELEMENT PROGRAM (CFG*)>
<!ATTLIST PROGRAM id NMTOKEN #REQUIRED>
<!ATTLIST PROGRAM name CDATA #REQUIRED>
<!ATTLIST PROGRAM entry NMTOKEN #REQUIRED>

<!ELEMENT CFG (NODE*, EDGE*, LOOP*, ATTRS_LIST*)>
<!ATTLIST CFG id NMTOKEN #REQUIRED>
<!ATTLIST CFG name CDATA #REQUIRED>
<!ATTLIST CFG startnode CDATA #REQUIRED>
<!ATTLIST CFG endnodes CDATA #REQUIRED>

<!ELEMENT NODE (INSTRUCTION*, ATTRS_LIST*)>
<!ATTLIST NODE id NMTOKEN #REQUIRED>
<!ATTLIST NODE type (BasicBlock | Call) #REQUIRED>

<!ELEMENT EDGE (ATTRS_LIST*)>
<!ATTLIST EDGE id NMTOKEN #REQUIRED>
<!ATTLIST EDGE origin NMTOKEN #REQUIRED>
<!ATTLIST EDGE destination NMTOKEN #REQUIRED>

<!ELEMENT LOOP (ATTRS_LIST*)>
<!ATTLIST LOOP id NMTOKEN #REQUIRED>
<!ATTLIST LOOP head NMTOKEN #REQUIRED>
<!ATTLIST LOOP nodes CDATA #REQUIRED>
<!ATTLIST LOOP backedges CDATA #REQUIRED>

<!ELEMENT INSTRUCTION (ATTRS_LIST*)>
<!ATTLIST INSTRUCTION id NMTOKEN #REQUIRED>
<!ATTLIST INSTRUCTION asm_type (Label | Directive | Code | Other) #REQUIRED>
<!ATTLIST INSTRUCTION code CDATA #REQUIRED>

<!ELEMENT ATTRS_LIST (ATTR*)>

<!-- **********************************************
      Attributes (modify the file to check
      the validity of your files containing added
      attributes
*************************************************** -->


<!ELEMENT ATTR (ACCES*|SP)>
<!ATTLIST ATTR type CDATA #REQUIRED>
<!ATTLIST ATTR name CDATA #REQUIRED>
<!ATTLIST ATTR value CDATA #IMPLIED>

<!-- ******* Other attribute tags, add new tags if required ************** -->

<!ATTLIST ATTR sizeframewithcaller NMTOKEN #IMPLIED>
<!ATTLIST ATTR sizeframewithoutcaller NMTOKEN #IMPLIED>

<!-- ******* Attribute output by the data address analyser *************** -->

<!ELEMENT ACCES (ADRSIZE)>
<!ATTLIST ACCES type CDATA #REQUIRED>
<!ATTLIST ACCES seg CDATA #REQUIRED>
<!ATTLIST ACCES varname CDATA #REQUIRED>
<!ATTLIST ACCES memoryByteAcceded NMTOKEN #REQUIRED>

<!ELEMENT ADRSIZE EMPTY>
<!ATTLIST ADRSIZE begin NMTOKEN #REQUIRED>
<!ATTLIST ADRSIZE size NMTOKEN #REQUIRED>

<!ELEMENT SP (CALLCONTEXT*)>
<!ATTLIST SP value NMTOKEN #REQUIRED>

<!ELEMENT CALLCONTEXT EMPTY>
<!ATTLIST CALLCONTEXT value CDATA #REQUIRED>

=== yixianUvA/extended_heptane_svn/benchmarks/bs/resDCacheL1.xml
<!DOCTYPE PROGRAM SYSTEM 'cfglib.dtd'>
<PROGRAM   id ="0"   name="bs"   entry="1" >
<CFG id="2"  name="__aeabi_idiv"  startnode="3"  endnodes="3, " >
  <NODE  id="3"  type="BasicBlock" >
  <INSTRUCTION  id="4"  asm_type="Code"  code="nop"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x8000" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  <INSTRUCTION  id="5"  asm_type="Code"  code="bx lr"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x8004" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  </NODE>

<ATTRS_LIST>
<ATTR type="ContextList" name="ContextList" >
</ATTR>
</ATTRS_LIST>
</CFG>
<CFG id="6"  name="__aeabi_i2d"  startnode="7"  endnodes="7, " >
  <NODE  id="7"  type="BasicBlock" >
  <INSTRUCTION  id="8"  asm_type="Code"  code="nop"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x8008" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  <INSTRUCTION  id="9"  asm_type="Code"  code="bx lr"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x800c" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  </NODE>

<ATTRS_LIST>
<ATTR type="ContextList" name="ContextList" >
</ATTR>
</ATTRS_LIST>
</CFG>
<CFG id="10"  name="__aeabi_uidivmod"  startnode="11"  endnodes="11, " >
  <NODE  id="11"  type="BasicBlock" >
  <INSTRUCTION  id="12"  asm_type="Code"  code="nop"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x8010" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  <INSTRUCTION  id="13"  asm_type="Code"  code="bx lr"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x8014" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  </NODE>

<ATTRS_LIST>
<ATTR type="ContextList" name="ContextList" >
</ATTR>
</ATTRS_LIST>
</CFG>
<CFG id="14"  name="__aeabi_fcmpge"  startnode="15"  endnodes="15, " >
  <NODE  id="15"  type="BasicBlock" >
  <INSTRUCTION  id="16"  asm_type="Code"  code="nop"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x8018" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  <INSTRUCTION  id="17"  asm_type="Code"  code="bx lr"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x801c" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  </NODE>

<ATTRS_LIST>
<ATTR type="ContextList" name="ContextList" >
</ATTR>
</ATTRS_LIST>
</CFG>
<CFG id="18"  name="__aeabi_i2f"  startnode="19"  endnodes="19, " >
  <NODE  id="19"  type="BasicBlock" >
  <INSTRUCTION  id="20"  asm_type="Code"  code="nop"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x8020" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  <INSTRUCTION  id="21"  asm_type="Code"  code="bx lr"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x8024" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  </NODE>

<ATTRS_LIST>
<ATTR type="ContextList" name="ContextList" >
</ATTR>
</ATTRS_LIST>
</CFG>
<CFG id="22"  name="__aeabi_ddiv"  startnode="23"  endnodes="23, " >
  <NODE  id="23"  type="BasicBlock" >
  <INSTRUCTION  id="24"  asm_type="Code"  code="nop"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x8028" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  <INSTRUCTION  id="25"  asm_type="Code"  code="bx lr"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x802c" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  </NODE>

<ATTRS_LIST>
<ATTR type="ContextList" name="ContextList" >
</ATTR>
</ATTRS_LIST>
</CFG>
<CFG id="26"  name="__aeabi_dsub"  startnode="27"  endnodes="27, " >
  <NODE  id="27"  type="BasicBlock" >
  <INSTRUCTION  id="28"  asm_type="Code"  code="nop"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x8030" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  <INSTRUCTION  id="29"  asm_type="Code"  code="bx lr"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x8034" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  </NODE>

<ATTRS_LIST>
<ATTR type="ContextList" name="ContextList" >
</ATTR>
</ATTRS_LIST>
</CFG>
<CFG id="30"  name="__aeabi_dmul"  startnode="31"  endnodes="31, " >
  <NODE  id="31"  type="BasicBlock" >
  <INSTRUCTION  id="32"  asm_type="Code"  code="nop"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x8038" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  <INSTRUCTION  id="33"  asm_type="Code"  code="bx lr"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x803c" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  </NODE>

<ATTRS_LIST>
<ATTR type="ContextList" name="ContextList" >
</ATTR>
</ATTRS_LIST>
</CFG>
<CFG id="34"  name="__aeabi_dcmpge"  startnode="35"  endnodes="35, " >
  <NODE  id="35"  type="BasicBlock" >
  <INSTRUCTION  id="36"  asm_type="Code"  code="nop"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x8040" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  <INSTRUCTION  id="37"  asm_type="Code"  code="bx lr"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x8044" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  </NODE>

<ATTRS_LIST>
<ATTR type="ContextList" name="ContextList" >
</ATTR>
</ATTRS_LIST>
</CFG>
<CFG id="38"  name="__aeabi_dcmpeq"  startnode="39"  endnodes="39, " >
  <NODE  id="39"  type="BasicBlock" >
  <INSTRUCTION  id="40"  asm_type="Code"  code="nop"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x8048" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  <INSTRUCTION  id="41"  asm_type="Code"  code="bx lr"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x804c" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  </NODE>

<ATTRS_LIST>
<ATTR type="ContextList" name="ContextList" >
</ATTR>
</ATTRS_LIST>
</CFG>
<CFG id="42"  name="__aeabi_dcmpgt"  startnode="43"  endnodes="43, " >
  <NODE  id="43"  type="BasicBlock" >
  <INSTRUCTION  id="44"  asm_type="Code"  code="nop"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x8050" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  <INSTRUCTION  id="45"  asm_type="Code"  code="bx lr"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x8054" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  </NODE>

<ATTRS_LIST>
<ATTR type="ContextList" name="ContextList" >
</ATTR>
</ATTRS_LIST>
</CFG>
<CFG id="46"  name="__aeabi_dcmple"  startnode="47"  endnodes="47, " >
  <NODE  id="47"  type="BasicBlock" >
  <INSTRUCTION  id="48"  asm_type="Code"  code="nop"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x8058" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  <INSTRUCTION  id="49"  asm_type="Code"  code="bx lr"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x805c" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  </NODE>

<ATTRS_LIST>
<ATTR type="ContextList" name="ContextList" >
</ATTR>
</ATTRS_LIST>
</CFG>
<CFG id="50"  name="__aeabi_d2f"  startnode="51"  endnodes="51, " >
  <NODE  id="51"  type="BasicBlock" >
  <INSTRUCTION  id="52"  asm_type="Code"  code="nop"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x8060" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  <INSTRUCTION  id="53"  asm_type="Code"  code="bx lr"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x8064" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  </NODE>

<ATTRS_LIST>
<ATTR type="ContextList" name="ContextList" >
</ATTR>
</ATTRS_LIST>
</CFG>
<CFG id="54"  name="__aeabi_dadd"  startnode="55"  endnodes="55, " >
  <NODE  id="55"  type="BasicBlock" >
  <INSTRUCTION  id="56"  asm_type="Code"  code="nop"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
      <ADDRSIZE  begin="0x8068" size="4"/>
  </ACCES>
</ATTR>
</ATTRS_LIST>
  </INSTRUCTION>
  <INSTRUCTION  id="57"  asm_type="Code"  code="bx lr"  >
<ATTRS_LIST>
<ATTR type="address" name="address">
  <ACCES type="read" seg="code" varname="" precision="1">
